//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SequenceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="vadikorzh.com.com.com", ConfigurationName="ServiceReference1.ISequenceServer")]
    public interface ISequenceServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="vadikorzh.com.com.com/ISequenceServer/Reset", ReplyAction="vadikorzh.com.com.com/ISequenceServer/ResetResponse")]
        void Reset();
        
        [System.ServiceModel.OperationContractAttribute(Action="vadikorzh.com.com.com/ISequenceServer/Reset", ReplyAction="vadikorzh.com.com.com/ISequenceServer/ResetResponse")]
        System.Threading.Tasks.Task ResetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="vadikorzh.com.com.com/ISequenceServer/Next", ReplyAction="vadikorzh.com.com.com/ISequenceServer/NextResponse")]
        int Next();
        
        [System.ServiceModel.OperationContractAttribute(Action="vadikorzh.com.com.com/ISequenceServer/Next", ReplyAction="vadikorzh.com.com.com/ISequenceServer/NextResponse")]
        System.Threading.Tasks.Task<int> NextAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="vadikorzh.com.com.com/ISequenceServer/Current", ReplyAction="vadikorzh.com.com.com/ISequenceServer/CurrentResponse")]
        int Current();
        
        [System.ServiceModel.OperationContractAttribute(Action="vadikorzh.com.com.com/ISequenceServer/Current", ReplyAction="vadikorzh.com.com.com/ISequenceServer/CurrentResponse")]
        System.Threading.Tasks.Task<int> CurrentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISequenceServerChannel : SequenceClient.ServiceReference1.ISequenceServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SequenceServerClient : System.ServiceModel.ClientBase<SequenceClient.ServiceReference1.ISequenceServer>, SequenceClient.ServiceReference1.ISequenceServer {
        
        public SequenceServerClient() {
        }
        
        public SequenceServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SequenceServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SequenceServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SequenceServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Reset() {
            base.Channel.Reset();
        }
        
        public System.Threading.Tasks.Task ResetAsync() {
            return base.Channel.ResetAsync();
        }
        
        public int Next() {
            return base.Channel.Next();
        }
        
        public System.Threading.Tasks.Task<int> NextAsync() {
            return base.Channel.NextAsync();
        }
        
        public int Current() {
            return base.Channel.Current();
        }
        
        public System.Threading.Tasks.Task<int> CurrentAsync() {
            return base.Channel.CurrentAsync();
        }
    }
}
